### ISSUE TITLE
Display event date duplicate

### ISSUE THREAD

**Issue by luukaass** [tarjmp/eventlab#106]
When an event starts and ends on the same date, should it be shown to the user twice like in the screenshot below? Alternatively, we could show June 13, 11:00 - 12:00.
![image](https://user-images.githubusercontent.com/39259570/59451502-e2101500-8e0b-11e9-9dd7-f5989bd4caa0.png)

**Comment by tarjmp** [comment]
Latter one would be fine 👍

**Comment by luukaass** [comment]
Okay, I will take care of it.

**Comment by luukaass** [comment]
Fixed 88eaceb2df965f0bcd46dd6eb88bfdde957a61a4
